from sqlalchemy import Column, String, ForeignKey, Integer, Text, DateTime, Float
from sqlalchemy.orm import relationship
from app.database import Base
from sqlalchemy import func
from pgvector.sqlalchemy import Vector


class User(Base):
  """
  Represents a registered user account.
  One user owns many documents and conversations - all data in the system is scoped to a user via user_id foreign keys.
  """
  __tablename__ = "users"

  id = Column(Integer, primary_key=True)
  email = Column(String, unique=True, nullable=False)
  hashed_password = Column(String, nullable=False)
  created_at = Column(DateTime, server_default=func.now())
  documents = relationship("Document", back_populates="user")
  conversations = relationship("Conversation", back_populates="user")

class Document(Base):
  """
  Represents a saved document in a user's knowledge base.

  Documents go through a lifecycle: processing -> ready or failed
  Raw content is stored here but is never returned in list/detail API responses to avoid sending large payloads.
  Cascade: deleting a document automatically deletes all its chunks via the SQLAlchemy relationship cascade and the DB-level ondelete.
  """
  __tablename__ = "documents"

  id = Column(Integer, primary_key=True)
  user_id = Column(Integer, ForeignKey("users.id"))
  title = Column(String, nullable=False)
  source_url = Column(String)
  raw_content = Column(Text)
  status = Column(String, default="processing")
  created_at = Column(DateTime, server_default=func.now())
  word_count = Column(Integer)
  chunk_count = Column(Integer)
  chunks = relationship("DocumentChunk", back_populates="document", cascade="all, delete-orphan")
  user = relationship('User', back_populates='documents')

  @property
  def excerpt(self) -> str | None:
    """First 200 characters of the content, for card previews."""
    if not self.raw_content:
      return None
    text = self.raw_content.strip()
    return text[:200] if len(text) > 200 else text

class DocumentChunk(Base):
  """
  Stores individual text chunks of a document alongside their vector embeddings.
  Each document is split into overlapping chunks during ingestion.
  The embedding column stores a 1536 dimensional vector generated by OpenAI's text-embedding-3-small model.
  ondelete="CASCADE": if the parent document is deleted at the DB-level, all its chunks are automatically deleted.
  """
  __tablename__ = "document_chunks"

  id = Column(Integer, primary_key=True)
  document_id = Column(Integer, ForeignKey("documents.id", ondelete="CASCADE"))
  chunk_text = Column(Text, nullable=False)
  chunk_index = Column(Integer)
  embedding = Column(Vector(1536))
  document = relationship("Document", back_populates="chunks")


class Conversation(Base):
  """
  Groups related messages into a single conversation thread.

  Title is set to be the first question asked - gives the conversation a meaningful label in the UI sidebar without requiring a separate title input from the user.

  Cascade: deleting a converation deletes all its messages, which cascade-deletes their sources via Message's own cascade
  """
  __tablename__ = "conversations"

  id = Column(Integer, primary_key=True)
  user_id = Column(Integer, ForeignKey("users.id"))
  title = Column(String)
  created_at = Column(DateTime, server_default=func.now())
  messages = relationship("Message", back_populates="conversation", cascade="all, delete-orphan", order_by="Message.id")
  user = relationship("User", back_populates="conversations")


class Message(Base):
  """
  Represents one message in a conversation - either a user question or an AI answer.
  "user": the question by the user and sources is always empty
  "Assistant": the AI-generated answer, sources contains cited documents

  Cascade: deleting a message deletes all its MessageSource citation rows.
  """
  __tablename__ = "messages"

  id = Column(Integer, primary_key=True)
  conversation_id = Column(Integer, ForeignKey("conversations.id"))
  role = Column(String)
  content = Column(Text)
  created_at = Column(DateTime, server_default=func.now())
  sources = relationship("MessageSource", back_populates="message", cascade="all, delete-orphan")
  conversation= relationship("Conversation", back_populates="messages")


class MessageSource(Base):
  """
  Tracks which documents were cited in an AI answer.

  One MessageSource row per unique document cited in an assistant message.

  The three @property methods bridge the gap between what Pydantic's
    SourceResponse schema expects (document_title, source_url, document_id)
    and what actually exists on this model (chunk → document → those fields).
  """
  __tablename__ = "message_sources"

  id = Column(Integer, primary_key=True)
  message_id = Column(Integer, ForeignKey("messages.id"))
  chunk_id = Column(Integer, ForeignKey("document_chunks.id", ondelete="SET NULL"), nullable=True)
  message = relationship("Message", back_populates="sources")
  chunk = relationship("DocumentChunk")

  @property
  def document_id(self):
    return self.chunk.document.id if self.chunk else None

  @property
  def document_title(self):
    return self.chunk.document.title if self.chunk else None

  @property
  def source_url(self):
    return self.chunk.document.source_url if self.chunk else None