"""Added properties to Document and MessageSource

Revision ID: 62a49af03cfd
Revises: e23f8f50a78d
Create Date: 2026-09-08 11:48:31.754794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62a49af03cfd'
down_revision: Union[str, Sequence[str], None] = 'e23f8f50a78d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
